### PR TITLE
Poopfolio

### PR DESCRIPTION
**Pull request by alexcrist**

### CODE REVIEW

**Comment by alexcrist** [comment]
@mleclair73 - Want to avoid this code getting stale, pls merge asap

**Comment by mleclair73** [comment]
Looks like you've got a typo in line 22 there! Happy to merge after

**Comment by tomkowalski** [comment]
This affects my workflow can you keep a legacy version of this page for us that depend on it?

**Comment by alexcrist** [comment]
Hi @mleclair73

I've updated this PR and fixed the aforementioned section of code here in this commit, https://github.com/mleclair73/resume-site/pull/1/commits/2ab2b1b92352cc69991c73831bf01054c7c47d01

Please merge this ASAP, this diagram below shows the severity of this bug and just how many customers are actually being affected by this...

**Customers / Customer (minutes) vs. 1 Minute * Person / Malcolm**

**Comment by mleclair73** [comment]
@alexcrist: I think I see what you're hoping to achieve [here](https://gph.is/2jAdoZw), but unfortunately 
the management team and I have come to a business decision that this isn't project isn't worth the continuing support costs and thus will need to be tabled. Please ensure that no further billable hours are charted to this account. This was a bold plan but ultimately isn't in our best interests at the moment. 

Please check out some customer stories we developed to evaluate the support costs:
[Customer 1](https://gph.is/2gj3Im3)
[Customer 2](https://gph.is/1McU9kO)
[Customer 3](https://gph.is/1ppshye)

**Pull request closed without merging**
